language: python

python:
    - 2.7
    - 3.6
env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - ASTROPY_VERSION=stable
        - NUMPY_VERSION=stable
        - CONDA_REQ_DEPENDENCIES='Cython jinja2 six setuptools'
        - CONDA_DEPENDENCIES='Cython jinja2 six setuptools'
        - SETUP_CMD='test'
        - MAIN_CMD='python setup.py'
        - PIP_DEPENDENCIES='pytest-catchlog git+https://github.com/alexrudy/lumberjack.git'
        - PIP_PYZMQ=yes
    matrix:
      - SETUP_CMD='egg_info'
      - SETUP_CMD='test'
matrix:
    include:
        # Pin python 2.6 to versions which are available on Conda.
        - python: 2.6
          env:
            - SETUP_CMD='test'
            - NUMPY_VERSION=1.9.2
            - ASTROPY_VERSION=1.0.3
            # Conda-astorpy-py26 bundled pytest is too old.
            - ASTROPY_USE_SYSTEM_PYTEST=yes 
        
        # Do a coverage test in Python 2.
        - python: 2.7
          env: SETUP_CMD='test --coverage'
          
        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: 
            - SETUP_CMD='build_sphinx -w'
            - CONDA_DEPENDENCIES="$CONDA_DEPENDENCIES sphinx<1.4"
          
        # Try without some optional deps
        - python: 2.7
          env: 
            - CONDA_DEPENDENCIES=$CONDA_REQ_DEPENDENCIES
            - PIP_PYZMQ=no
          
        - python: 3.6
          env: 
            - CONDA_DEPENDENCIES=$CONDA_REQ_DEPENDENCIES
            - PIP_PYZMQ=no
          

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

install:
    # CI-Helpers
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
    - if [[ $PIP_PYZMQ == 'yes' ]]; then pip install --no-binary pyzmq pyzmq
    
script:
   - $MAIN_CMD $SETUP_CMD

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='Cauldron/tests/coveragerc'; fi
